### ISSUE TITLE
Inviting User to Group

### ISSUE THREAD

**Issue by 5v3nn** [sopra-fs24-group07/sopra-fs24-group-07-server#10]
As a group member, 
I want to invite a new user to the group 
in order to add a new member to the group and start collaborating with them.

Acceptance Criteria: 
- [x] A user can invite new members to a group.
- [ ] Invitation is accomplished by email
- [x] Registered users are directly added
- [x] Unregistered users are sent a link with a token to register (without a mail, e.g. over whatsapp)

---

Frontend
- [x] sopra-fs24-group07/sopra-fs24-group-07-client#18
- [x] sopra-fs24-group07/sopra-fs24-group-07-server#58

Backend
- [x] sopra-fs24-group07/sopra-fs24-group-07-server#57
- [x] #86
- [x] #91

**Comment by 5v3nn** [comment]
mail management will be implemented in the #139
