### ISSUE TITLE
User Profile

### ISSUE THREAD

**Issue by 5v3nn** [sopra-fs24-group07/sopra-fs24-group-07-server#11]
ID: 9

As a logged in user, 
I want to view a user profile 
in order to see the user’s data like username, email.

Acceptance Criteria: 
- [x] A user can visit their own user profile 
- [x] The profile shows certain data on the user. 

---
Frontend:
- [x] sopra-fs24-group07/sopra-fs24-group-07-client#25
- [x] sopra-fs24-group07/sopra-fs24-group-07-client#26
- [x] sopra-fs24-group07/sopra-fs24-group-07-client#27

Backend:
- [x] #78
- [x] #79

**Comment by 5v3nn** [comment]
done (for one dev task we wont implement, because no value for our application)
