### ISSUE TITLE
Modify tasks

### ISSUE THREAD

**Issue by B1s9l** [sopra-fs24-group07/sopra-fs24-group-07-server#116]
As a group member, 
I want to edit new group tasks 
in order to share with the group what projects need to be worked on.
I want to modify group tasks

Acceptance criteria:
- [x] Edit tasks
- [ ] Sync tasks

---

Frontend:
- [x] sopra-fs24-group07/sopra-fs24-group-07-client#7
- [x] #117
- [ ] sopra-fs24-group07/sopra-fs24-group-07-client/issues/74

Backend:
- [x] sopra-fs24-group07/sopra-fs24-group-07-server#110
- [x] sopra-fs24-group07/sopra-fs24-group-07-server#111
- [x] #118

**Comment by 5v3nn** [comment]
impediment: found yesterday a bug, for which the time is not eought this week, so will fix this in sprint 2, but created new dev taks for this fix here
