### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by 5v3nn** [sopra-fs24-group07/sopra-fs24-group-07-server#13]
As a user, 
I want to be able to message other users or groups 
in order to enhance collaboration and coordination on a specific task.

Acceptance Criteria: 
- [x] A user can select a task and add comments. 
- [x] The comments should be visible to all other users of the group (because noone else can see the task)
- [x] The comments should be visible in descending date order (newest comment on top)
- [x] the user should be able to delete comments

---

Frontend
- [x] sopra-fs24-group07/sopra-fs24-group-07-client#10
- [x] sopra-fs24-group07/sopra-fs24-group-07-client#11
- [x] #134
- [x] https://github.com/sopra-fs24-group07/sopra-fs24-group-07-client/issues/72

Backend
- [x] sopra-fs24-group07/sopra-fs24-group-07-server#40
- [x] sopra-fs24-group07/sopra-fs24-group-07-server#41
- [x] sopra-fs24-group07/sopra-fs24-group-07-server#42
- [x] sopra-fs24-group07/sopra-fs24-group-07-server#133
- [x] #135
- [x] #153
- [x] #157
