### ISSUE TITLE
User Experience

### ISSUE THREAD

**Issue by 5v3nn** [sopra-fs24-group07/sopra-fs24-group-07-server#144]
As a user
I want an intuitive user interface
so that I know what to do.

Acceptance criterias
- [x]  Pop ups as defined in the mockups (full screen)
- [x] Text fields are in their respective boxes
- [x] DB text length constraints make more sense

---

Frontend
- [x] sopra-fs24-group07/sopra-fs24-group-07-client#67
- [x] sopra-fs24-group07/sopra-fs24-group-07-client#141
- [x] sopra-fs24-group07/sopra-fs24-group-07-client#66
- [x] sopra-fs24-group07/sopra-fs24-group-07-client#143
- [x] sopra-fs24-group07/sopra-fs24-group-07-client#68
- [x] sopra-fs24-group07/sopra-fs24-group-07-client#110
- [x] sopra-fs24-group07/sopra-fs24-group-07-client#173

Backend
- [x] sopra-fs24-group07/sopra-fs24-group-07-server#148

**Comment by 5v3nn** [comment]
done and tested
