### ISSUE TITLE
Bugfix

### ISSUE THREAD

**Issue by 5v3nn** [sopra-fs24-group07/sopra-fs24-group-07-server#149]
As a user
I do not want to encounter bugs
So that i can have a nice experience.

PLACEHOLDER, BECAUSE FOR BUGS WE ENCOUTER DURING M2

---

Frontend
- [x] sopra-fs24-group07/sopra-fs24-group-07-client#113
- [x] sopra-fs24-group07/sopra-fs24-group-07-client#130

Backend
- [x] sopra-fs24-group07/sopra-fs24-group-07-server#182
- [x] #214
- [x] #220

**Comment by 5v3nn** [comment]
all fixed
