### ISSUE TITLE
Session overview for each team

### ISSUE THREAD

**Issue by B1s9l** [sopra-fs24-group07/sopra-fs24-group-07-server#158]
As a user
I want to open a session overview
so that I see all session my team has had in the past.

Acceptance criterias
- [x]  Pop ups in the same style as others
- [x] Pop up can be opened through a button on the dashboard
- [x] Shows session history
- [x] Includes additional analysis of sessions such as total time, all end times

---

Frontend
- [x] sopra-fs24-group07/sopra-fs24-group-07-client#76
- [x] sopra-fs24-group07/sopra-fs24-group-07-client#77
- [x] sopra-fs24-group07/sopra-fs24-group-07-client#78

Backend
- [x] #174

**Comment by 5v3nn** [comment]
done and tested
