### ISSUE TITLE
Agora Token Generation

### ISSUE THREAD

**Issue by 5v3nn** [sopra-fs24-group07/sopra-fs24-group-07-server#187]
As a user
I want the best security for the voice chat
such that noone can hijack my session voice chat.

- [x] Agora token generation in backend

---

Frontend
- [x] sopra-fs24-group07/sopra-fs24-group-07-client#112

Backend
- [x] sopra-fs24-group07/sopra-fs24-group-07-server#188
- [x] sopra-fs24-group07/sopra-fs24-group-07-server#189
- [x] sopra-fs24-group07/sopra-fs24-group-07-server#190
- [x] #202

**Comment by 5v3nn** [comment]
done and tested
