### ISSUE TITLE
Voice Chat

### ISSUE THREAD

**Issue by 5v3nn** [sopra-fs24-group07/sopra-fs24-group-07-server#36]
As a User
I want a voice chat
In order to talk to my team members

Acceptance Criterias
- [x] Agora integration
- [x] Voice chat visualizations in UI
- [x] Signal who is talking

---

Frontend
- [x] sopra-fs24-group07/sopra-fs24-group-07-client#15
- [x] sopra-fs24-group07/sopra-fs24-group-07-client#14
- [x] sopra-fs24-group07/sopra-fs24-group-07-client#75

Backend
- [x] #50
- [x] #51

**Comment by 5v3nn** [comment]
signal who is talkin will be done in sprint2

**Comment by 5v3nn** [comment]
implemented as specified
