### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by 5v3nn** [sopra-fs24-group07/sopra-fs24-group-07-server#4]
As an existing User, 
I want to login to my account 
in order to be able to use the application.

Acceptance Criteria: 
- [x] To successfully log-in to an account the unique identifier and the password must be correct. 
- [x] Only logged-in users can navigate the application or make any further use of the tools.

---

Frontend
- [x] sopra-fs24-group07/sopra-fs24-group-07-client#3
- [x] sopra-fs24-group07/sopra-fs24-group-07-client#4

Backend
- [x] sopra-fs24-group07/sopra-fs24-group-07-server#16
- [x] sopra-fs24-group07/sopra-fs24-group-07-server#15
- [x] sopra-fs24-group07/sopra-fs24-group-07-server#17

**Comment by 5v3nn** [comment]
done
