### ISSUE TITLE
Sessions

### ISSUE THREAD

**Issue by 5v3nn** [sopra-fs24-group07/sopra-fs24-group-07-server#7]
ID: 5

As a group member, 
I want to start a session 
in order to work together with my colleagues in real-time.

Acceptance Criteria: 
- [x] Each member can start a session. 
- [x] A session has a time goal
- [x] A session will sync real time with all members at its start, track the time of its duration.

---
Frontend:
- [x] sopra-fs24-group07/sopra-fs24-group-07-client#21
- [x] sopra-fs24-group07/sopra-fs24-group-07-client#22
- [x] sopra-fs24-group07/sopra-fs24-group-07-client#23
- [x] sopra-fs24-group07/sopra-fs24-group-07-client#24

Backend:
- [x] #68
- [x] #71
- [x] #72
- [x] #73
- [x] #69

**Comment by 5v3nn** [comment]
done (small changes in the acceptance criteras to what is actually needed)
