### ISSUE TITLE
Session - Time tracking

### ISSUE THREAD

**Issue by 5v3nn** [sopra-fs24-group07/sopra-fs24-group-07-server#8]
ID: 6

As a group member, 
I want to track time on the group session 
in order to track progress.

Acceptance Criteria: 
- [x] A session start starts a timer which will be added to the total time tracked. 
- [x] Session timer is visible to all users in the group
- [x] Timer should be visible in real time for each user in the session.
- [x] Each group member should see sum of past sessions and their time. 

---
Frontend:
(very closely connected to "Sessions" see the following 2 tasks:)
- [x] sopra-fs24-group07/sopra-fs24-group-07-client#23

Backend:
- [x] #74
- [x] #70

**Comment by 5v3nn** [comment]
see #158  for further improvement on session
