### ISSUE TITLE
Create Tasks

### ISSUE THREAD

**Issue by 5v3nn** [sopra-fs24-group07/sopra-fs24-group-07-server#9]
As a group member, 
I want to create new group tasks 
in order to share with the group what projects need to be worked on.

Acceptance Criteria: 
- [x] A user can create tasks on a task board. 
- [x] A task has a title and a description. 
- [x] All group members can see their respective groups tasks.

---

Frontend
- [x] sopra-fs24-group07/sopra-fs24-group-07-client#9
- [x] sopra-fs24-group07/sopra-fs24-group-07-client#8
- [x] sopra-fs24-group07/sopra-fs24-group-07-client#109

Backend
- [x] sopra-fs24-group07/sopra-fs24-group-07-server#32
- [x] sopra-fs24-group07/sopra-fs24-group-07-server#33
- [x] sopra-fs24-group07/sopra-fs24-group-07-server#35
- [x] sopra-fs24-group07/sopra-fs24-group-07-server#108
- [x] sopra-fs24-group07/sopra-fs24-group-07-server#109
- [x] sopra-fs24-group07/sopra-fs24-group-07-server#183
- [x] sopra-fs24-group07/sopra-fs24-group-07-server#110
- [x] sopra-fs24-group07/sopra-fs24-group-07-server#111

**Comment by 5v3nn** [comment]
done and tested
